name: cruise
description: A RSS article read Flutter application.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  meta: ^1.1.8
  flutter_svg: 0.22.0
  logger: 1.0.0
  scoped_model: ^1.1.0
  shrine_images: ^1.1.2
  flare_dart: 2.3.4
  flare_flutter: ^2.0.2
  vector_math: ^2.0.8
  collection: ^1.14.0
  package_info: ^0.4.0
  flutter_staggered_grid_view: ^0.3.0
  adaptive_breakpoints: ^0.0.2
  cupertino_icons: 1.0.4
  http: 0.13.1
  timeago: 3.0.2
  animations: 2.0.0
  flutter_hooks: 0.16.0
  share: 2.0.1
  shimmer: 1.1.1
  crypto: 3.0.0
  url_launcher: 6.0.2
  uni_links: 0.4.0
  shared_preferences: 2.0.5
  state_notifier: 0.7.0
  flutter_slidable: 0.6.0
  pull_to_refresh: 2.0.0
  country_code_picker: 2.0.1
  dio: 4.0.0
  global_configuration: 2.0.0-nullsafety.1
  hive_flutter: 1.0.0
  eva_icons_flutter: 3.0.0
  fish_redux: 0.3.7
  wheel:
    git:
      url: https://github.com/jiangxiaoqiang/wheel.git
      ref: main
  flutter_html: 3.0.0-alpha.5
  video_player: 2.3.0

dependency_overrides:
  flutter_secure_storage: 4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  path:
  args:
  pedantic: ^1.9.0
  string_scanner: ^1.0.5

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - images/Icon-App-83.5x83.5@3x.png
    - assets/cfg/

