name: cruise
description: A RSS article read Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  meta: ^1.1.8
  flutter_svg: ^0.20.0-nullsafety.3
  logger: 0.9.4
  scoped_model: ^1.1.0
  shrine_images: ^1.1.2
  flare_dart: 2.3.4
  flare_flutter: ^2.0.2
  vector_math: ^2.0.8
  collection: ^1.14.0
  package_info: ^0.4.0
  fluttertoast: 8.0.3
  #google_fonts: 1.0.0
  flutter_staggered_grid_view: ^0.3.0
  adaptive_breakpoints: ^0.0.2
  cupertino_icons: 1.0.0
  http: ^0.12.0+2
  flutter_icons: ^1.0.0
  timeago: 3.0.2
  animations: 2.0.0
  flutter_hooks: 0.16.0
  share: 2.0.1
  shimmer: 1.1.1
  crypto: 2.1.5
  url_launcher: 6.0.2
  uni_links: 0.4.0
  flutter_html: 1.3.0
  shared_preferences: 2.0.5
  state_notifier: ^0.5.0
  flutter_secure_storage: 4.1.0
  flutter_slidable: 0.5.7
  hive: ^1.4.1+1
  pull_to_refresh: 1.6.4
  country_code_picker: 2.0.1
  dio: 3.0.10
  fish_redux: 0.3.7
  hive_flutter: 0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  path:
  args:
  grinder: ^0.8.0
  pedantic: ^1.9.0
  string_scanner: ^1.0.5

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
